version: "3.9"

name: Enterprise_Chat_Assistant_with_RAG

services:
  api:
    build:
      context: ./apps/api
    env_file:
      - ./apps/api/.env
    ports:
      - "8080:8080"
    volumes:
      - ./apps/api/serviceAccount.json:/app/serviceAccount.json:ro
      - docs-data:/data/docs
    depends_on:
      inference:
        condition: service_healthy
    environment:
      # Optional override for local
      - CORS_ORIGIN=http://localhost:5173
      - INFERENCE_BASE_URL=http://inference:8000
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  inference:
    build:
      context: ./apps/inference
    env_file:
      - ./apps/inference/.env
    ports:
      - "8000:8000"
    volumes:
      - index-data:/data/index
      - docs-data:/data/docs
    environment:
      - INDEX_DIR=/data/index
      - DOCS_DIR=/data/docs
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
    environment:
      - VITE_API_BASE=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  # Optional: Neo4j for graph loader (workers/neo4j-loader)
  neo4j:
    image: neo4j:5.23
    environment:
      - NEO4J_AUTH=neo4j/pass
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    profiles: ["graph"]

volumes:
  index-data:
  docs-data:
  neo4j-data:
